### PR TITLE
Get ancestor for displaying dependency tree in relationships

### PR DESCRIPTION
**Pull request by tarun06**
This pr is required by https://github.com/microsoft/sbom-tool/pull/457 which display Hierarchy of package dependency in relatrionship section of SBOM

### CODE REVIEW

**Comment by cobya** [comment]
@tarun06 What does this look like in an example ScanManifest output? I'm worried about this change's impact on downstream dependencies

**Comment by tarun06** [comment]
[ScanManifest.json](https://github.com/microsoft/component-detection/files/13739344/ScanManifest.json)
[ScanManifest_WithChange.json](https://github.com/microsoft/component-detection/files/13739345/ScanManifest_WithChange.json)


yes, @cobya it does change topLevelReferrers.. Sharing scanmanifest for reference

**Comment by cobya** [comment]
@tarun06 would you be able to come to [Community Meeting 01-03-2024](https://github.com/microsoft/component-detection/discussions/919) to discuss? I'd like to get some more context on the change

**Comment by tarun06** [comment]
> @tarun06 would you be able to come to [Community Meeting 01-03-2024](https://github.com/microsoft/component-detection/discussions/919) to discuss? I'd like to get some more context on the change

Sure.. Thank you

**Comment by tarun06** [comment]
> > @tarun06 would you be able to come to [Community Meeting 01-03-2024](https://github.com/microsoft/component-detection/discussions/919) to discuss? I'd like to get some more context on the change
> 
> Sure.. Thank you

@cobya i joned the community meeting now..  I am 1 hour late thinking the meeting is at 11:30 IST, Appologies for that.. Let me know if i can answer to queries here. :)

**Comment by cobya** [comment]
Sure, a couple of things then so we can do this async:
- How is SBOM tool planning on using the ancestors information? Parse the graph by looking at each ancestor to see which is the root for each level?
- Should we keep this as the existing field or add it as a new one? I'm preferential to a new field because it can be useful to have both sets of information (i.e. give me the full graph vs give me only the component which brings this one)
- If you are planning on having TopLevelReferrers become the list of ancestors, we should rename it since it's not really accurate anymore

**Comment by tarun06** [comment]
> Sure, a couple of things then so we can do this async:
> 
> * How is SBOM tool planning on using the ancestors information? Parse the graph by looking at each ancestor to see which is the root for each level?
> * Should we keep this as the existing field or add it as a new one? I'm preferential to a new field because it can be useful to have both sets of information (i.e. give me the full graph vs give me only the component which brings this one)
> * If you are planning on having TopLevelReferrers become the list of ancestors, we should rename it since it's not really accurate anymore



> * How is SBOM tool planning on using the ancestors information? Parse the graph by looking at each ancestor to see which is the root for each level?

**The SBOM tool creates a record of the dependency hierarchy for each package, assigning a unique identifier to each. Developers can easily identify how a transitive dependency is included in their application. Also for fixing security vulnerabilities, teams can identify which package they need to upgrade to resolve the vulnerability on a transitive dependency.**

 
example -> SPDXRef-RootPackage -> Microsoft.EntityFrameworkCore -> Microsoft.Extensions.Caching.Memory ->Microsoft.Extensions.Caching.Abstractions -> Microsoft.Extensions.Primitives -> System.Runtime.CompilerServices.Unsafe


> * Should we keep this as the existing field or add it as a new one? I'm preferential to a new field because it can be useful to have both sets of information (i.e. give me the full graph vs give me only the component which brings this one)

**We can create a new field as well.. I opted for "TopLevelReferrers" as I believed it closely resembled its intended meaning. please suggest any name if you have it in mind. Thanks**

**Comment by tarun06** [comment]
> > Sure, a couple of things then so we can do this async:
> > 
> > * How is SBOM tool planning on using the ancestors information? Parse the graph by looking at each ancestor to see which is the root for each level?
> > * Should we keep this as the existing field or add it as a new one? I'm preferential to a new field because it can be useful to have both sets of information (i.e. give me the full graph vs give me only the component which brings this one)
> > * If you are planning on having TopLevelReferrers become the list of ancestors, we should rename it since it's not really accurate anymore
> 
> > * How is SBOM tool planning on using the ancestors information? Parse the graph by looking at each ancestor to see which is the root for each level?
> 
> **The SBOM tool creates a record of the dependency hierarchy for each package, assigning a unique identifier to each. Developers can easily identify how a transitive dependency is included in their application. Also for fixing security vulnerabilities, teams can identify which package they need to upgrade to resolve the vulnerability on a transitive dependency.**
> 
> example -> SPDXRef-RootPackage -> Microsoft.EntityFrameworkCore -> Microsoft.Extensions.Caching.Memory ->Microsoft.Extensions.Caching.Abstractions -> Microsoft.Extensions.Primitives -> System.Runtime.CompilerServices.Unsafe

Please check the SBOM PR for complete spdx file generated using this aproach https://github.com/microsoft/sbom-tool/pull/457
> 
> > * Should we keep this as the existing field or add it as a new one? I'm preferential to a new field because it can be useful to have both sets of information (i.e. give me the full graph vs give me only the component which brings this one)
> 
> **We can create a new field as well.. I opted for "TopLevelReferrers" as I believed it closely resembled its intended meaning. please suggest any name if you have it in mind. Thanks**

**Comment by tarun06** [comment]
> > Sure, a couple of things then so we can do this async:
> > 
> > * How is SBOM tool planning on using the ancestors information? Parse the graph by looking at each ancestor to see which is the root for each level?
> > * Should we keep this as the existing field or add it as a new one? I'm preferential to a new field because it can be useful to have both sets of information (i.e. give me the full graph vs give me only the component which brings this one)
> > * If you are planning on having TopLevelReferrers become the list of ancestors, we should rename it since it's not really accurate anymore
> 
> > * How is SBOM tool planning on using the ancestors information? Parse the graph by looking at each ancestor to see which is the root for each level?
> 
> **The SBOM tool creates a record of the dependency hierarchy for each package, assigning a unique identifier to each. Developers can easily identify how a transitive dependency is included in their application. Also for fixing security vulnerabilities, teams can identify which package they need to upgrade to resolve the vulnerability on a transitive dependency.**
> 
> example -> SPDXRef-RootPackage -> Microsoft.EntityFrameworkCore -> Microsoft.Extensions.Caching.Memory ->Microsoft.Extensions.Caching.Abstractions -> Microsoft.Extensions.Primitives -> System.Runtime.CompilerServices.Unsafe Please check the SBOM PR for complete spdx file generated using this aproach [microsoft/sbom-tool#457](https://github.com/microsoft/sbom-tool/pull/457)
> 
> > * Should we keep this as the existing field or add it as a new one? I'm preferential to a new field because it can be useful to have both sets of information (i.e. give me the full graph vs give me only the component which brings this one)
> 
> **We can create a new field as well.. I opted for "TopLevelReferrers" as I believed it closely resembled its intended meaning. please suggest any name if you have it in mind. Thanks**

taging @cobya

**Comment by cobya** [comment]
@tarun06 I think we should keep `TopLevelReferrers` as the list of explicit root only components (the top only), and we can make the new field something like `AncestralReferrers` (I'm not sold on that, if you have something better feel free) that way anyone who depends on `TopLevelReferrers` being only root components is unaffected as well.

**Comment by tarun06** [comment]
@cobya i have used AncestralReferrers instead of TopLevelReferrers .. Please review.

**Review by cobya — APPROVED** [review]

**Pull request merged**
