### PR TITLE
Support target specific cargo dependencies

### PR DESCRIPTION
**Pull request by tevoinea**
Adds support for capturing platform specific dependencies[^1].

cc: @danielframpton who first raised this issue in another repository (thank you!)

[^1]: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies

### CODE REVIEW

**Comment by tevoinea** [comment]
Snapshot verification failures are expected because there are platform specific dependencies in our verification repo. The number of components shouldn't change because they all get picked up in `cargo.lock` but the number of explicitly referenced components should change because we're now scanning them in `cargo.toml`.

Previous run total: [7047](https://github.com/microsoft/component-detection/runs/4607747234?check_suite_focus=true#step:16:1048)
Current run total: [7047](https://github.com/microsoft/component-detection/runs/4609348167?check_suite_focus=true#step:16:1048)

Previous run explicitly referenced for cargo v2: [45](https://github.com/microsoft/component-detection/runs/4607747234?check_suite_focus=true#step:16:1044)
Current run explicitly referenced for cargo v2: **[47](https://github.com/microsoft/component-detection/runs/4609348167?check_suite_focus=true#step:16:1044)**

**Review by JamieMagee — APPROVED** [review]

**Comment by JamieMagee** [comment]
@tevoinea The latest run of snapshot verification has a maven component change in there_

**Comment by tevoinea** [comment]
> @tevoinea The latest run of snapshot verification has a maven component change in there?

@JamieMagee Probably transient or a version drift issue, rerunning to check.

**Comment by JamieMagee** [comment]
@tevoinea do you have capacity to deconflict this? If not, let me know and I'll get around to it.

**Comment by tevoinea** [comment]
@JamieMagee I don't right now sorry, I skimmed it and it seems like just RustCrateUtilities that needs any 'actual' conflict resolution.

**Comment by cobya** [comment]
@tevoinea I did some conflict resolution (sorry for the delay, Jamie got distracted). Can you do a quick check and verify everything looks correct?

**Comment by tevoinea** [comment]
@cobya The logic looks right to me! Just don't forget to bump the detector version number

**Pull request merged**
