### PR TITLE
Strong-name the assemblies

### PR DESCRIPTION
**Pull request by dfederm**
This strong-names the assemblies so that applications which are themselves strong-named can use these libraries.

The snk file was generated by running: `sn -k StrongName.snk`

### CODE REVIEW

**Comment by JamieMagee** [comment]
@dfederm Are we okay to still merge this, even if we're blocked with upstream dependencies?

**Comment by JamieMagee** [comment]
I opened a PR upstream https://github.com/dotnet/Docker.DotNet/pull/567

**Comment by JamieMagee** [comment]
PR merged upstream. Waiting for a release now.

**Comment by JamieMagee** [comment]
Version `3.125.13` was released upstream with the required strong-naming 🎉

**Comment by JamieMagee** [comment]
See #453

**Comment by JamieMagee** [comment]
@dfederm can you rebase this branch please? I don't have permissions to push to your fork, but I've created a branch you can reset to: [`strong-naming`][1].

We're getting closer, but the build still fails due to a lack of strong named assemblies for [Tomlyn][2] and [Valleysoft.DockerfileModel][3]. I've created issues upstream:

- https://github.com/xoofx/Tomlyn/issues/56
- https://github.com/mthalman/DockerfileModel/issues/101

I'll also create pull requests when I have time.

[1]: https://github.com/microsoft/component-detection/tree/strong-naming
[2]: https://github.com/xoofx/Tomlyn
[3]: https://github.com/mthalman/DockerfileModel

**Comment by FernandoRojo** [comment]
Closing for now as unneeded, but we can revisit if there is more need for strong-naming in the future.

**Pull request closed without merging**
