### PR TITLE
ci: replace verification repository

### LINKED ISSUE #44: Replace verification repository
In order to verify changes, we have a verification GitHub action[^1] which scans a project for each detector for each pull request. This allows us to easily see if we are detecting more or less components.

Currently, this workflow uses a private repository which uses git submodules to point to specific commits in open source projects. Instead, we should checkout the open source projects to the specific commit required during our GitHub Actions workflow.

Current repos in our verification suite include:

- https://github.com/flutter/flutter/commit/48ba488d3
- https://github.com/OpenIntelWireless/HeliPort/commit/bbcfb72
- https://github.com/helm/helm/commit/1b0a26ff
- https://github.com/Workday/warp-core/commit/3581e25
- https://github.com/vtsynergy/SeqInCloud/commit/441480d
- https://github.com/andybrodie/xml2csv/commit/dd0ca9b
- https://github.com/apache/maven/commit/5fbe40a33
- https://github.com/expressjs/express/commit/5596222f
- https://github.com/Azure/azure-sdk-for-net/commit/1bf85a0ae2
- https://www.nuget.org/packages/Moq/4.14.5
- https://github.com/tensorflow/recommenders/commit/09309e1 (with frozen lockfile)
- https://github.com/pnpm/pnpm/commit/393293900
- https://github.com/PyCQA/isort/commit/44e3b5d179da5033ce23f796b014e74f3a3259cd
- https://github.com/QueueClassic/queue_classic/commit/1e40ddd
- https://github.com/deptofdefense/HAS-Qualifier-Challenges/tree/master/spacerace/kubos
- https://github.com/microsoft/snocat/commit/d453860
- https://github.com/sharkdp/bat/commit/e4df564
- https://github.com/rust-lang/cargo/commit/e4b65bdc8
- https://github.com/electron/electron/commit/e6fbbf432
- https://github.com/microsoft/TypeScript-Website/commit/0cf75e2db696597827eadac6ae10ebee36ebfd23

[^1]: https://github.com/microsoft/component-detection/actions/workflows/verify-snapshot.yml

### PR DESCRIPTION
**Pull request by JamieMagee**
This PR migrates from using a private repository, componendetection-verification, and moves verification tests into this repo. The verification tests have been rewritten to be minimal projects that exercise all functionality of a detector.

The current verification tests are expected to fail in this PR as the most recent snapshots are for the old verification projects.

Closes #44

### CODE REVIEW

**Comment by jcfiorenzano** [comment]
The verification repo for pip has to have the dependencies freeze:
These are the steps that need to be followed for pip
```
You can't just run "pip freeze" from a normal terminal, this captures what's in your global environment instead of what's coming locally.

Instead you want to:

Create a new virtual env (see [here](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/))
Activate the virtual env
pip install -r requirements.txt
pip freeze
Pip freeze will write out to a console, so you can either pipe to a requirements.txt or copy paste.
```

**Review by jcfiorenzano — CHANGES_REQUESTED** [review]
The verification repo for pip has to have the dependencies freeze:
These are the steps that need to be followed for pip
```
Instead you want to:

Create a new virtual env (see [here](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/))
Activate the virtual env
pip install -r requirements.txt
pip freeze
Pip freeze will write out to a console, so you can either pipe to a requirements.txt.
```

**Comment by jcfiorenzano** [comment]
I would also add the steps to the Contribution (or README) about how to add a new verification repo

**Comment by JamieMagee** [comment]
After discussing with @jcfiorenzano, I've decided to create some synthetic verification/integration/e2e tests instead. Checking out other repositories is flaky, and overall not a reliable method for this style of test.

**Comment by jcfiorenzano** [comment]
There is a file `ivi.jar` at the repo root. Is that intendend?

**Comment by jcfiorenzano** [comment]
I would add a note in this document https://github.com/microsoft/component-detection/blob/main/docs/creating-a-new-detector.md. Explaining how and where to add a new verification repo.

**Review by jcfiorenzano — APPROVED** [review]

**Comment by JamieMagee** [comment]
> There is a file `ivi.jar` at the repo root. Is that intendend?

Good catch. It's left over from testing locally

> I would add a note in this document [`main`/docs/creating-a-new-detector.md](https://github.com/microsoft/component-detection/blob/main/docs/creating-a-new-detector.md?rgh-link-date=2022-02-01T22%3A44%3A45Z). Explaining how and where to add a new verification repo.

Will do!

**Pull request merged**
