### PR TITLE
Support renamed dependencies in Cargo.toml

### PR DESCRIPTION
**Pull request by tofay**
Cargo supports renamed dependencies in Cargo.toml: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml

component-detection currently misses such dependencies, as it uses the renamed dependency name when determining what the root dependencies on. This PR updates component detection to use the real dependency name in such cases.

### CODE REVIEW

**Comment by JamieMagee** [comment]
@tofay Sorry for the delay. Can you deconflict your PR?

**Comment by tofay** [comment]
No problem, I've rebased.

**Comment by JamieMagee** [comment]
Thanks, this all looks good to me.

We recently moved our integration tests into this repo as well. Could you plese add a test case [here](https://github.com/microsoft/component-detection/blob/main/test/Microsoft.ComponentDetection.VerificationTests/resources/rust/standard/Cargo.toml) as well?

I'll approve in the meantime, so we can merge this soon after.

**Comment by tofay** [comment]
I've updated the standard verification test to have a renamed dependency.

**Review by JamieMagee — APPROVED** [review]

**Pull request merged**
